### ISSUE TITLE
If you're not passing anybody, get out of the passing lane

### ISSUE THREAD

**Issue by spilth** [ckundo/principles#6]
There might be somebody behind that wants to pass you.

This goes for driving, bicycling and walking.

**Comment by ckundo** [comment]
The scope on this is really broad. I'm willing to take on aspects of this, but can you please narrow it down?

**Comment by spilth** [comment]
If you're literally driving in the passing lane and not actively passing anybody you should get out of the passing lane - get to the right (or your countries equivalent direction) and let others pass you.
